# Generated by Django 4.2.3 on 2023-07-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("A2Zbackend", "0005_dispatchentry_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispatchentry",
            name="partner_caseid",
        ),
    ]
