# Generated by Django 4.2.3 on 2023-07-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("A2Zbackend", "0007_remove_dispatchentry_repair_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispatchentry",
            name="is_scheduled",
        ),
    ]
