# Generated by Django 4.2.3 on 2023-07-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("A2Zbackend", "0009_remove_dispatchentry_eta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispatchentry",
            name="scheduled_date",
        ),
    ]
