# Generated by Django 4.2.3 on 2023-07-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("A2Zbackend", "0010_remove_dispatchentry_scheduled_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispatchentry",
            name="source",
        ),
    ]
