# Generated by Django 4.2.3 on 2023-07-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("A2Zbackend", "0011_remove_dispatchentry_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispatchentry",
            name="ata",
        ),
    ]
