# Generated by Django 4.2.3 on 2023-07-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("A2Zbackend", "0013_remove_dispatchentryassets_colorid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dispatchentryassets",
            old_name="license_state",
            new_name="vehicle_class",
        ),
        migrations.RenameField(
            model_name="dispatchentryassets",
            old_name="body_type_id",
            new_name="vehicle_type",
        ),
        migrations.RemoveField(
            model_name="dispatchentryassets",
            name="license_year",
        ),
        migrations.RemoveField(
            model_name="dispatchentryassets",
            name="model_year",
        ),
    ]
