# Generated by Django 4.2.3 on 2023-07-24 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "A2Zbackend",
            "0014_rename_license_state_dispatchentryassets_vehicle_class_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispatchentryassets",
            name="make",
        ),
        migrations.RemoveField(
            model_name="dispatchentryassets",
            name="vehicle_class",
        ),
        migrations.RemoveField(
            model_name="dispatchentryassets",
            name="vehicle_type",
        ),
        migrations.AddField(
            model_name="dispatchentryassets",
            name="vehicle_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="A2Zbackend.vehicles",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dispatchentry",
            name="service_type_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="A2Zbackend.servicetypes",
            ),
        ),
    ]
