# Generated by Django 4.2.3 on 2023-07-25 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("A2Zbackend", "0015_remove_dispatchentryassets_make_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispatchentryassets",
            name="dispatch_entry_id",
        ),
    ]
