# Generated by Django 4.2.3 on 2023-07-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("A2Zbackend", "0016_remove_dispatchentryassets_dispatch_entry_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicles",
            name="vehicle_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
