# Generated by Django 4.2.3 on 2023-07-26 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("A2Zbackend", "0018_alter_accounts_account_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rateitem",
            old_name="budget_2w",
            new_name="default_rate",
        ),
        migrations.RemoveField(
            model_name="rateitem",
            name="budget_4w",
        ),
        migrations.RemoveField(
            model_name="rateitem",
            name="default_rate_2w",
        ),
        migrations.RemoveField(
            model_name="rateitem",
            name="default_rate_4w",
        ),
        migrations.RemoveField(
            model_name="rateitem",
            name="luxury_2w",
        ),
        migrations.RemoveField(
            model_name="rateitem",
            name="luxury_4w",
        ),
        migrations.RemoveField(
            model_name="rateitem",
            name="premium_2w",
        ),
        migrations.RemoveField(
            model_name="rateitem",
            name="premium_4w",
        ),
        migrations.RemoveField(
            model_name="rateitem",
            name="suv_4w",
        ),
    ]
