# Generated by Django 4.2.3 on 2023-07-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("A2Zbackend", "0019_rename_budget_2w_rateitem_default_rate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="systemuser",
            old_name="csr_id",
            new_name="id",
        ),
        migrations.AddField(
            model_name="systemuser",
            name="authToken",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
