# Generated by Django 4.2.3 on 2023-08-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("A2Zbackend", "0020_rename_csr_id_systemuser_id_systemuser_authtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchentry",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispatchentry",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
